'use strict';

// То что он бдует проверять, и не будет переписывать.
// То есть базовая хйня, которая сломает нахй всё, если переписать, или типо того.

// Known browser/JS API properties:
const KNOWN_API_PROPS = new Set([
    // Object
    'prototype','constructor','__proto__','hasOwnProperty','toString','valueOf',
    'toLocaleString','isPrototypeOf','propertyIsEnumerable',
    // Function
    'call','apply','bind','arguments','caller','length','name',
    // Array
    'push','pop','shift','unshift','splice','slice','concat','join','reverse',
    'sort','map','filter','reduce','reduceRight','forEach','find','findIndex',
    'includes','indexOf','lastIndexOf','some','every','flat','flatMap','fill',
    'entries','keys','values','at','copyWithin','from','isArray','of',
    // String
    'charAt','charCodeAt','codePointAt','startsWith','endsWith','repeat',
    'padStart','padEnd','trim','trimStart','trimEnd','split','replace','replaceAll',
    'match','matchAll','search','toLowerCase','toUpperCase','substring','substr',
    'slice','normalize','localeCompare','at','raw',
    // Number
    'toFixed','toPrecision','toExponential','isInteger','isFinite','isNaN','isSafeInteger',
    // Math
    'abs','ceil','floor','round','max','min','pow','sqrt','cbrt','hypot',
    'random','sin','cos','tan','asin','acos','atan','atan2','log','log2','log10',
    'exp','sign','trunc','clz32','imul','fround','PI','E','LN2','LN10','LOG2E',
    'LOG10E','SQRT2','SQRT1_2',
    // JSON
    'parse','stringify',
    // Date
    'now','getTime','getFullYear','getMonth','getDate','getDay','getHours',
    'getMinutes','getSeconds','getMilliseconds','setTime','setFullYear',
    'toISOString','toUTCString','toLocaleString','toLocaleDateString','toLocaleTimeString',
    // RegExp
    'test','exec','source','flags','global','multiline','ignoreCase','sticky',
    'unicode','dotAll','lastIndex',
    // Promise
    'then','catch','finally','resolve','reject','all','allSettled','any','race',
    // Map/Set
    'get','set','has','delete','clear','size','forEach','entries','keys','values',
    // Error
    'message','stack','code','cause',
    // DOM — Element
    'getElementById','getElementsByClassName','getElementsByTagName',
    'querySelector','querySelectorAll','createElement','createTextNode',
    'createDocumentFragment','createEvent',
    'appendChild','removeChild','insertBefore','replaceChild','cloneNode',
    'contains','closest','matches','remove','prepend','append','before','after',
    'replaceWith','insertAdjacentHTML','insertAdjacentElement','insertAdjacentText',
    'innerHTML','outerHTML','textContent','innerText','outerText',
    'getAttribute','setAttribute','removeAttribute','hasAttribute',
    'getAttributeNode','setAttributeNode','toggleAttribute',
    'classList','className','style','id','tagName','nodeName','nodeType','nodeValue',
    'dataset','attributes',
    'parentNode','parentElement','children','childNodes','childElementCount',
    'firstChild','lastChild','firstElementChild','lastElementChild',
    'nextSibling','previousSibling','nextElementSibling','previousElementSibling',
    'scrollTop','scrollLeft','scrollWidth','scrollHeight','scrollTo','scrollBy',
    'scrollIntoView','clientWidth','clientHeight','clientTop','clientLeft',
    'offsetWidth','offsetHeight','offsetTop','offsetLeft','offsetParent',
    'getBoundingClientRect','getComputedStyle',
    'focus','blur','click','submit','reset','select',
    'addEventListener','removeEventListener','dispatchEvent',
    // DOM — Document
    'head','body','documentElement','title','cookie','referrer','domain',
    'readyState','contentType','doctype','forms','images','links','scripts',
    'activeElement','fullscreenElement','pointerLockElement',
    'write','writeln','open','close','execCommand',
    'parseFromString',
    // DOM — Window
    'innerWidth','innerHeight','outerWidth','outerHeight',
    'scrollX','scrollY','pageXOffset','pageYOffset',
    'screenX','screenY','screenLeft','screenTop',
    'devicePixelRatio','frameElement','frames',
    'opener','parent','self','top','closed',
    'getSelection','matchMedia','moveBy','moveTo','resizeBy','resizeTo',
    'requestAnimationFrame','cancelAnimationFrame',
    'setTimeout','setInterval','clearTimeout','clearInterval',
    'requestIdleCallback','cancelIdleCallback',
    'atob','btoa','fetch','postMessage',
    'alert','confirm','prompt','print',
    'open','close','stop','focus','blur',
    // Events
    'type','target','currentTarget','eventPhase','bubbles','cancelable','composed',
    'defaultPrevented','isTrusted','timeStamp','detail',
    'preventDefault','stopPropagation','stopImmediatePropagation',
    'clientX','clientY','pageX','pageY','screenX','screenY','offsetX','offsetY',
    'movementX','movementY','button','buttons','altKey','ctrlKey','metaKey','shiftKey',
    'key','keyCode','charCode','which','repeat','isComposing','inputType',
    'deltaX','deltaY','deltaZ','deltaMode',
    'touches','targetTouches','changedTouches',
    'data','origin','lastEventId','source','ports',
    'dataTransfer','clipboardData','relatedTarget',
    'animationName','elapsedTime','propertyName','pseudoElement',
    'oldURL','newURL','oldValue','newValue','storageArea',
    'loaded','total','lengthComputable',
    // Style properties
    'cssText','setProperty','getPropertyValue','removeProperty',
    'backgroundColor','color','display','position','width','height','top','left',
    'right','bottom','padding','paddingTop','paddingRight','paddingBottom','paddingLeft',
    'margin','marginTop','marginRight','marginBottom','marginLeft',
    'border','borderTop','borderRight','borderBottom','borderLeft',
    'borderRadius','borderColor','borderWidth','borderStyle',
    'fontSize','fontFamily','fontWeight','fontStyle','lineHeight','letterSpacing',
    'textAlign','textDecoration','textTransform','textIndent','textShadow',
    'whiteSpace','wordWrap','wordBreak','overflowWrap',
    'cursor','overflow','overflowX','overflowY',
    'visibility','opacity','zIndex','pointerEvents','userSelect',
    'background','backgroundImage','backgroundSize','backgroundRepeat',
    'backgroundPosition','backgroundAttachment','backgroundClip','backgroundOrigin',
    'boxSizing','boxShadow','outline','outlineColor','outlineStyle','outlineWidth',
    'float','clear','content',
    'transform','transformOrigin','transition','transitionDuration','transitionProperty',
    'transitionTimingFunction','transitionDelay',
    'animation','animationName','animationDuration','animationDelay',
    'animationTimingFunction','animationIterationCount','animationDirection',
    'animationFillMode','animationPlayState',
    'flex','flexDirection','flexWrap','flexFlow','flexGrow','flexShrink','flexBasis',
    'alignItems','alignContent','alignSelf','justifyContent','justifyItems','justifySelf',
    'gap','rowGap','columnGap','order',
    'gridTemplateColumns','gridTemplateRows','gridColumn','gridRow','gridArea',
    'gridGap','gridAutoFlow','gridAutoColumns','gridAutoRows',
    'maxWidth','maxHeight','minWidth','minHeight',
    'verticalAlign','tableLayout','borderCollapse','borderSpacing',
    'listStyle','listStyleType','listStylePosition','listStyleImage',
    'objectFit','objectPosition','resize','appearance','filter',
    'backdropFilter','mixBlendMode','isolation','willChange','contain',
    // Canvas
    'getContext','canvas','fillStyle','strokeStyle','lineWidth','lineCap','lineJoin',
    'miterLimit','lineDashOffset','setLineDash','getLineDash',
    'fillRect','strokeRect','clearRect','beginPath','closePath','moveTo','lineTo',
    'bezierCurveTo','quadraticCurveTo','arc','arcTo','ellipse','rect','roundRect',
    'fill','stroke','clip','isPointInPath','isPointInStroke',
    'fillText','strokeText','measureText','font','textBaseline',
    'drawImage','createImageData','getImageData','putImageData',
    'createLinearGradient','createRadialGradient','createConicGradient','createPattern',
    'addColorStop','save','restore','scale','rotate','translate',
    'setTransform','resetTransform','globalAlpha','globalCompositeOperation',
    'shadowBlur','shadowColor','shadowOffsetX','shadowOffsetY','imageSmoothingEnabled',
    'toDataURL','toBlob','transferControlToOffscreen',
    // WebSocket
    'url','protocol','extensions','bufferedAmount','binaryType',
    'send','close','onopen','onclose','onmessage','onerror','readyState',
    'CONNECTING','OPEN','CLOSING','CLOSED',
    // Fetch / XHR / Request / Response
    'method','headers','body','mode','credentials','cache','redirect',
    'referrerPolicy','integrity','keepalive','signal',
    'ok','status','statusText','url','type','redirected','bodyUsed',
    'json','text','blob','arrayBuffer','formData','clone',
    'abort','getAllResponseHeaders','getResponseHeader','setRequestHeader',
    'overrideMimeType','upload','response','responseText','responseType','responseURL',
    'responseXML','timeout','withCredentials','onreadystatechange','onload',
    'onloadstart','onloadend','onprogress','ontimeout','onabort',
    // Storage
    'getItem','setItem','removeItem','key','clear','length',
    // Navigator
    'userAgent','platform','language','languages','vendor','appName','appVersion',
    'onLine','cookieEnabled','hardwareConcurrency','maxTouchPoints',
    'geolocation','mediaDevices','serviceWorker','clipboard','permissions',
    'vibrate','sendBeacon','share','canShare',
    // Location
    'href','hostname','pathname','search','hash','port','origin',
    'assign','reload','replace',
    // History
    'pushState','replaceState','go','back','forward','state',
    // Console
    'log','warn','error','info','debug','trace','dir','dirxml','table',
    'count','countReset','group','groupCollapsed','groupEnd',
    'time','timeEnd','timeLog','timeStamp','profile','profileEnd',
    'assert','clear',
    // ArrayBuffer / TypedArray
    'byteLength','byteOffset','buffer','BYTES_PER_ELEMENT',
    'subarray','copyWithin','set',
    // DataView
    'getInt8','getUint8','getInt16','getUint16','getInt32','getUint32',
    'getFloat32','getFloat64','getBigInt64','getBigUint64',
    'setInt8','setUint8','setInt16','setUint16','setInt32','setUint32',
    'setFloat32','setFloat64','setBigInt64','setBigUint64',
    // Node.js globals
    'require','module','exports','__dirname','__filename','process',
    'exit','env','argv','cwd','pid','stdin','stdout','stderr',
    'on','once','off','emit','pipe','unpipe','destroy','write','end','read',
    'createReadStream','createWriteStream','readFile','writeFile','readFileSync',
    'writeFileSync','existsSync','mkdirSync','readdirSync','statSync',
    'unlink','rename','stat','mkdir','readdir',
    // Misc
    'toJSON','Symbol','iterator','asyncIterator','toPrimitive','toStringTag',
    'description','for',
    'parseFromString',
    // Image / Link / Script
    'src','alt','complete','naturalWidth','naturalHeight','decode','loading',
    'href','rel','media','disabled','async','defer','crossOrigin','integrity',
    'charset','content',
    // Input
    'value','checked','selected','disabled','readOnly','required','placeholder',
    'min','max','step','pattern','multiple','accept','files','validity',
    'checkValidity','reportValidity','setCustomValidity',
    // Form
    'action','method','enctype','encoding','elements','noValidate',
    // Select / Option
    'options','selectedIndex','selectedOptions','add',
    'label','defaultSelected','index',
    // Table
    'rows','cells','tHead','tFoot','tBodies','createTHead','createTFoot',
    'createCaption','insertRow','deleteRow','insertCell','deleteCell',
    'caption','cellPadding','cellSpacing',
    // Audio / Video
    'play','pause','load','canPlayType','currentTime','duration','paused',
    'ended','muted','volume','playbackRate','defaultPlaybackRate',
    'autoplay','loop','controls','preload','currentSrc','networkState',
    'buffered','seekable','seeking','played',
    // Web Audio
    'createOscillator','createGain','createAnalyser','createBiquadFilter',
    'createBuffer','createBufferSource','destination','sampleRate',
    'frequency','detune','gain','connect','disconnect','start',
    // WebGL
    'drawArrays','drawElements','createShader','createProgram','shaderSource',
    'compileShader','attachShader','linkProgram','useProgram','createBuffer',
    'bindBuffer','bufferData','enableVertexAttribArray','vertexAttribPointer',
    'getAttribLocation','getUniformLocation','uniform1f','uniform2f','uniform3f',
    'uniform4f','uniformMatrix4fv','viewport','enable','disable','blendFunc',
    'depthFunc','cullFace','createTexture','bindTexture','texImage2D','texParameteri',
    'activeTexture','generateMipmap','pixelStorei','clearColor','clearDepth',
    // Misc DOM
    'add','remove','toggle','contains','item','replace','supports','forEach',
    'contentWindow','contentDocument','srcdoc','sandbox','allow',
    'naturalWidth','naturalHeight','currentSrc',
    'shadowRoot','attachShadow','host','mode',
    'assignedSlot','assignedNodes','assignedElements',
    'animate','getAnimations','computedStyleMap',
    'observedAttributes','connectedCallback','disconnectedCallback',
    'adoptedCallback','attributeChangedCallback',
    // Observers
    'observe','unobserve','disconnect','takeRecords',
    'root','rootMargin','threshold','thresholds',
    'isIntersecting','intersectionRatio','intersectionRect',
    'boundingClientRect','rootBounds','time',
    'addedNodes','removedNodes','attributeName','attributeNamespace',
    'previousSibling','nextSibling','oldValue',
    'contentRect','borderBoxSize','contentBoxSize','devicePixelContentBoxSize',
    'inlineSize','blockSize',
]);

// JS keywords + global constructors:
const RESERVED = new Set([
    'break','case','catch','continue','debugger','default','delete','do','else',
    'finally','for','function','if','in','instanceof','new','return','switch',
    'this','throw','try','typeof','var','void','while','with','class','const',
    'enum','export','extends','import','super','implements','interface','let',
    'package','private','protected','public','static','yield','await','async',
    'of','get','set','from','as','true','false','null','undefined',
    'window','document','console','Math','JSON','Date','Array','Object','String',
    'Number','Boolean','RegExp','Error','TypeError','RangeError','SyntaxError',
    'ReferenceError','URIError','EvalError','AggregateError',
    'Map','Set','WeakMap','WeakSet','WeakRef','FinalizationRegistry',
    'Promise','Proxy','Reflect','Symbol',
    'Int8Array','Uint8Array','Uint8ClampedArray','Int16Array','Uint16Array',
    'Int32Array','Uint32Array','Float32Array','Float64Array',
    'BigInt64Array','BigUint64Array',
    'ArrayBuffer','SharedArrayBuffer','DataView','Atomics',
    'BigInt','globalThis','NaN','Infinity',
    'isNaN','isFinite','parseInt','parseFloat','eval',
    'encodeURI','decodeURI','encodeURIComponent','decodeURIComponent',
    'setTimeout','setInterval','clearTimeout','clearInterval',
    'requestAnimationFrame','cancelAnimationFrame',
    'alert','confirm','prompt','fetch','XMLHttpRequest',
    'WebSocket','EventSource','Worker','SharedWorker','ServiceWorker',
    'Blob','File','FileReader','FileList',
    'FormData','URL','URLSearchParams','Headers','Request','Response',
    'AbortController','AbortSignal',
    'performance','navigator','location','history','screen',
    'localStorage','sessionStorage','indexedDB',
    'Event','CustomEvent','MouseEvent','KeyboardEvent','TouchEvent',
    'FocusEvent','InputEvent','WheelEvent','PointerEvent',
    'AnimationEvent','TransitionEvent','DragEvent','ClipboardEvent',
    'MessageEvent','ErrorEvent','ProgressEvent','StorageEvent','PopStateEvent',
    'HashChangeEvent','BeforeUnloadEvent','PageTransitionEvent',
    'HTMLElement','Element','Node','NodeList','HTMLCollection',
    'Text','Comment','DocumentFragment','DOMParser',
    'MutationObserver','IntersectionObserver','ResizeObserver','PerformanceObserver',
    'Image','Audio','Video','MediaStream','MediaRecorder',
    'AudioContext','OfflineAudioContext',
    'WebGLRenderingContext','WebGL2RenderingContext',
    'CanvasRenderingContext2D','OffscreenCanvas',
    'TextEncoder','TextDecoder','crypto','CryptoKey','SubtleCrypto',
    'Intl','Notification','BroadcastChannel','MessageChannel','MessagePort',
    'ReadableStream','WritableStream','TransformStream',
    'queueMicrotask','structuredClone','reportError',
    'require','module','exports','__dirname','__filename','process','Buffer','global',
    'arguments',
]);
